<?php

/// 屬性 方法
class umi47OO
{
    protected $speed;     //屬性  public private  物件等級擁有的屬性
    const var1 = 123;
    static $counter = 0;  //類別等級的屬性  //
    public function __construct($initspeed = 0)
    {   //建構式 建構方法  建構子  一個物件指呼叫一次
        $this->speed = $initspeed;
        self::$counter++;
        echo $initspeed . 'Parent:__construct<br>';
    }
    public function upspeed()
    {
        $this->speed = $this->speed < 1 ? 1 : $this->speed * 1.2;
    }
    public function downspeed()
    {
        $this->speed = $this->speed < 1 ? 0 : $this->speed * 0.7;
    }
    public function getspeed()
    {
        return $this->speed;
    }
}

class Scooter extends umi47OO{
    // Override


    public $gear = 1;
    function __construct(int $initspeed = 0)
    {
        parent::__construct($initspeed);
        echo $initspeed.'self:__construct<br>';
    }

    function upspeed($gear =1)
    {   parent::upspeed(); // TODO: Change the autogenerated stub
        $this->gear = $gear;
        $this->speed *= 1.7*$this->gear;
    }
}

class people
{
    public $bike;

    public function setBike()
    {
        $this->bike = new umi47OO();
    }

    public function upBikespeed()
    {
        $this->bike->upspeed();
    }

    public function downBikespeed()
    {
        $this->bike->downspeed();
    }

    public function displayBikespeed()
    {
        return $this->bike->getspeed();
    }
}

class Twid
{   private $id;
    private $gender;
    private $area;
    private static $letters = 'ABCDEFGHJKLMNPQRSTUVXYWZIO';

    public function __construct($id = '',$gender = true, $area = -1)
    {   if (strlen($id) != 0) {
            if(self::checkTWid($id)){
                $this->id = $id;
            }else{
                throw new Exception('error id');
            }
        } else {
            $area = $area==-1?rand(0,25):$area;         ///如果沒有輸入地區就亂數產生
            $this->area = $area;
            $this->createNewId($gender, $area);
        }
    }
    private function createNewId($gender, $area){ /// 物件級別可以取用類別級別
        $id = substr(self::$letters,$area,1);
        $id .= $gender?'1':'2';
        $this->gender = $gender;
        for($i=0;$i<7;$i++){
            $id .= rand(0,9);
        }
        for($i=0;$i<10;$i++){
            if(self::checkTWid($id . $i)){
                $this->id = $id.$i;
                break;}
        }
    }

    public static function checkTWid($twid)
    {
        $ret = false;
        if (preg_match('/^[A-Z][12][0-9]{8}$/', $twid)) {

            $c1 = substr($twid, 0, 1);
            $n12 = strpos(self::$letters, $c1) + 10;
            $n1 = (int)($n12 / 10);
            $n2 = $n12 % 10;
            $n3 = substr($twid, 1, 1);
            $n4 = substr($twid, 2, 1);
            $n5 = substr($twid, 3, 1);
            $n6 = substr($twid, 4, 1);
            $n7 = substr($twid, 5, 1);
            $n8 = substr($twid, 6, 1);
            $n9 = substr($twid, 7, 1);
            $n10 = substr($twid, 8, 1);
            $n11 = substr($twid, 9, 1);

            $sum = 1 * $n1 + 9 * $n2 + 8 * $n3 + 7 * $n4 + 6 * $n5 + 5 * $n6 + 4 * $n7 + 3 * $n8 + 2 * $n9 + 1 * $n10 + 1 * $n11;
            $ret = ($sum % 10) == 0;
        }
        return $ret;
    }

    public function getGender()
    {
        return $this->gender;
    }
    public function getArea()
    {
        return substr(self::$letters,$this->area,1);
    }
    public function getId(){
        return $this->id;
    }
}
//getter & setter

class Member{  // 封裝底下set get
    private $id ,$name, $age ,$gender;
    function __construct($id){
        $this->id =$id;
        echo $this->id.'<br>';
    }

    function __get($nname){     //if $fname = 'id'
        if($nname == 'name'){
            $ret ='III' . $this->$nname;   // this->id
        }else{
        $ret =  $this->$nname;  } // this->id
        return $ret;
    }
    function __set($nname, $value){
//        if($fname != 'id'){
           $this->$nname = $value;
//        }

    }
}

?>